#!/bin/sh -l

set -e

: "${FORMAT:="text"}"
: "${CHANGE_TARGET:="master"}"
: "${TARGET:="origin/${CHANGE_TARGET}"}"

test -n "${CONTINUOUS_INTEGRATION}" && FORMAT="json"

/app/bin/pronto run -c "${TARGET}" -f "${FORMAT}" "$@"
