#!/bin/sh -l

set -e

: "${FORMAT:="text"}"
: "${CHANGE_TARGET:="master"}"
: "${TARGET:="origin/${CHANGE_TARGET}"}"

test -n "${CONTINUOUS_INTEGRATION}" && FORMAT="json"

# PRONTO_GITHUB_ACCESS_TOKEN=${GITHUB_TOKEN} \
#   PRONTO_PULL_REQUEST_ID=${CHANGE_ID} \
/app/bin/pronto run -c "${TARGET}" -f "${FORMAT}" "$@"
